const projects = [
  {
    id: 1,
    projectName: 'Eiffel Tower Structural Maintenance',
    siteLocation: 'Paris, France',
    region: 'Europe',
    primaryLanguage: 'French',
    projectDescription: 'Restoration and reinforcement of the Eiffel Tower steel framework.',
    materialCost: 400000,
    laborCost: 150000,
    equipmentCost: 80000,
    permitCost: 50000,
    logisticsCost: 30000,
    currencyCode: 'EUR',
  },
  {
    id: 2,
    projectName: 'Tokyo Smart Office Tower Construction',
    siteLocation: 'Tokyo, Japan',
    region: 'Asia',
    primaryLanguage: 'Japanese',
    projectDescription: 'Construction of a high-tech commercial skyscraper with integrated smart systems.',
    materialCost: 800000,
    laborCost: 200000,
    equipmentCost: 90000,
    permitCost: 0,
    logisticsCost: 40000,
    currencyCode: 'JPY',
  },
  {
    id: 3,
    projectName: 'Cairo Nile Bridge Expansion',
    siteLocation: 'Cairo, Egypt',
    region: 'Africa',
    primaryLanguage: 'Arabic',
    projectDescription: 'Expansion and reinforcement of a key Nile River transportation bridge.',
    materialCost: 150000,
    laborCost: 100000,
    equipmentCost: 50000,
    permitCost: 25000,
    logisticsCost: 20000,
    currencyCode: 'EGP',
  },
  {
    id: 4,
    projectName: 'Manhattan Urban Development Complex',
    siteLocation: 'New York, United States',
    region: 'North America',
    primaryLanguage: 'English',
    projectDescription: 'Construction of a multi-use commercial and residential complex in Manhattan.',
    materialCost: 600000,
    laborCost: 250000,
    equipmentCost: 120000,
    permitCost: 100000,
    logisticsCost: 50000,
    currencyCode: 'USD',
  },
  {
    id: 5,
    projectName: 'Sydney Waterfront Public Redevelopment',
    siteLocation: 'Sydney, Australia',
    region: 'Australia',
    primaryLanguage: 'English',
    projectDescription: 'Redevelopment of waterfront areas including parks, walkways, and public facilities.',
    materialCost: 900000,
    laborCost: 180000,
    equipmentCost: 70000,
    permitCost: 60000,
    logisticsCost: 35000,
    currencyCode: 'AUD',
  },
  {
    id: 6,
    projectName: 'Rio Coastal Highway Construction',
    siteLocation: 'Rio de Janeiro, Brazil',
    region: 'South America',
    primaryLanguage: 'Portuguese',
    projectDescription: 'Construction of a new coastal highway to support regional transportation growth.',
    materialCost: 700000,
    laborCost: 120000,
    equipmentCost: 60000,
    permitCost: 40000,
    logisticsCost: 25000,
    currencyCode: 'BRL',
  },
  {
    id: 7,
    projectName: 'Rome Historic Restoration Initiative',
    siteLocation: 'Rome, Italy',
    region: 'Europe',
    primaryLanguage: 'Italian',
    projectDescription: 'Restoration of historic public structures and heritage pathways.',
    materialCost: 350000,
    laborCost: 130000,
    equipmentCost: 75000,
    permitCost: 50000,
    logisticsCost: 30000,
    currencyCode: 'EUR',
  },
];

module.exports = { projects };
