// Simple mock project data
const projects = [
  {
    id: 1,
    projectName: 'Eiffel Tower Renovation',
    siteLocation: 'Paris, France',
    region: 'Europe',
    primaryLanguage: 'French',
    projectDescription: 'Structural maintenance and modernization of the iconic Eiffel Tower.',
    materialCost: 400000,
    laborCost: 150000,
    equipmentCost: 80000,
    permitCost: 50000,
    logisticsCost: 30000,
    currencyCode: 'EUR',
  },
  {
    id: 2,
    projectName: 'Tokyo High-Rise Development',
    siteLocation: 'Tokyo, Japan',
    region: 'Asia',
    primaryLanguage: 'Japanese',
    projectDescription: 'Construction of a 60-floor commercial skyscraper in downtown Tokyo.',
    materialCost: 800000,
    laborCost: 200000,
    equipmentCost: 90000,
    permitCost: 0,
    logisticsCost: 40000,
    currencyCode: 'JPY',
  },
  {
    id: 3,
    projectName: 'Nile River Bridge Expansion',
    siteLocation: 'Cairo, Egypt',
    region: 'Africa',
    primaryLanguage: 'Arabic',
    projectDescription: 'Expansion of a major transportation bridge across the Nile River.',
    materialCost: 150000,
    laborCost: 100000,
    equipmentCost: 50000,
    permitCost: 25000,
    logisticsCost: 20000,
    currencyCode: 'EGP',
  },
  {
    id: 4,
    projectName: 'Manhattan Commercial Complex',
    siteLocation: 'New York, United States',
    region: 'North America',
    primaryLanguage: 'English',
    projectDescription: 'Development of a multi-building commercial complex in Manhattan.',
    materialCost: 600000,
    laborCost: 250000,
    equipmentCost: 120000,
    permitCost: 100000,
    logisticsCost: 50000,
    currencyCode: 'USD',
  },
  {
    id: 5,
    projectName: 'Sydney Waterfront Redevelopment',
    siteLocation: 'Sydney, Australia',
    region: 'Australia',
    primaryLanguage: 'English',
    projectDescription: 'Redevelopment of waterfront spaces and public infrastructure.',
    materialCost: 900000,
    laborCost: 180000,
    equipmentCost: 70000,
    permitCost: 60000,
    logisticsCost: 35000,
    currencyCode: 'AUD',
  },
  {
    id: 6,
    projectName: 'Rio Coastal Road Project',
    siteLocation: 'Rio de Janeiro, Brazil',
    region: 'South America',
    primaryLanguage: 'Portuguese',
    projectDescription: 'Construction of a new coastal roadway to support tourism expansion.',
    materialCost: 700000,
    laborCost: 120000,
    equipmentCost: 60000,
    permitCost: 40000,
    logisticsCost: 25000,
    currencyCode: 'BRL',
  },
  {
    id: 7,
    projectName: 'Rome Historic District Restoration',
    siteLocation: 'Rome, Italy',
    region: 'Europe',
    primaryLanguage: 'Italian',
    projectDescription: 'Restoration of historic city structures and public walkways.',
    materialCost: 350000,
    laborCost: 130000,
    equipmentCost: 75000,
    permitCost: 50000,
    logisticsCost: 30000,
    currencyCode: 'EUR',
  },
];

module.exports = { projects };
